### ISSUE TITLE
Script (.fsx) tooltips aren't complete

### ISSUE THREAD

**Issue by Rhywun** [ionide/ionide-vscode-fsharp#1090]
Function and method tooltips in .fsx files aren't as useful as they could be.

Steps to reproduce the behaviour:
1. Create a new console project, look at a tooltip for `printfn` (1st screenshot)
2. Add a script file and look at a tooltip for `printfn` (2nd screenshot). It is missing what I feel are the most helpful infos - the Description and Returns sections. Also the parameter list is different - it doesn't describe the `format` parameter. 

 - OS: macOS 10.14.4
 - Ionide version: 3.36.1
 - VSCode version: 1.33.1
 - dotnet SDK version: netcoreapp2.1
 - mono / .Net Framework version: mono 5.18.1.3

Thanks

<img width="453" alt="Screen1" src="https://user-images.githubusercontent.com/1157174/57236801-d30b9b00-6ff3-11e9-8e73-c16b38e0bd45.png">
<img width="459" alt="Screen2" src="https://user-images.githubusercontent.com/1157174/57236802-d30b9b00-6ff3-11e9-9494-db09f4a0504c.png">

**Comment by LukeBurgessYeo** [comment]
This is still an issue in the latest release of ionide, however when I built and ran the most recent master branch  - with the latest FSAC also built locally - this issue was fixed. So presumably it's been fixed in the latest version of FSAC?

**Comment by Krzysztof-Cieslak** [comment]
I have no idea, we haven’t been working on this in particular. It may got fixed “accidentally” for some reasons (like updated FCS)

**Comment by LukeBurgessYeo** [comment]
Just checked the new release of Ionide (4.6.0), tool tips still don't seem to be working in .fsx files. I'll do a bit more digging when I get a chance.

![image](https://user-images.githubusercontent.com/15360369/74919562-aa0d9880-53c2-11ea-817a-238c16f936dc.png)

**Comment by baronfel** [comment]
the problem is that the xml documentation for FSharp.Core isn't located beside the FSharp.Core we use for FSI typechecking: https://github.com/dotnet/sdk/issues/13590

This problem can only be permanently fixed by the SDK team, but an interim fix is to copy the XML docs for FSharp.Core from your nuget cache to the SDK install directory for F#: `<dotnet sdk root>/<sdk version>/FSharp`

**Comment by baronfel** [comment]
Fun fact, this is also broken in VS! See https://github.com/dotnet/fsharp/issues/2926 for details :)

**Comment by Krzysztof-Cieslak** [comment]
Well, we can't fix it here anyway. Ionide/FSAC is doing the correct thing, it's SDK that doesn't provide enough info. Closing.

**Comment by baronfel** [comment]
It's worth trying with 5.0.101, which was released after my fix got in.

**Comment by baronfel** [comment]
It may have been released after the work was merged, but it doesn't include that fix yet. So looks like we're waiting for the next one.

**Comment by cartermp** [comment]
It is fixed for me on my machine, but I believe I have the updated .NET SDK as well that was installed via a VS preview:

**Comment by cartermp** [comment]
![image](https://user-images.githubusercontent.com/6309070/102927540-065ea000-444c-11eb-9715-53194c3e0257.png)

So this is resolved, just a matter of the SDK update itself flowing through. I believe it will either be fully released at the end of the month or when VS 16.9 releases. I don't know the policy of shipping it specifically but it falls under one of those release chains.

Either way there's no problem in Ionide or FSAC here

**Comment by PunkIslamist** [comment]
Hello,

for me this issue still exists today. I am using dotnet SDK version 6.0.111 on Linux, with the most recent release versions of VS Code and the Ionide extension.
Tooltips work in general, e.g. for `System.IO.File.ReadLines()`, but not for things in FSharp.Core. See the following pictures, both taken from the same FSX file.

![image](https://user-images.githubusercontent.com/26367652/206872242-9a15a4a1-f79e-46d3-b29e-0aff4d398cde.png)

![image](https://user-images.githubusercontent.com/26367652/206872258-1cd1e3c4-6a46-41ee-9de8-b595b0c89426.png)
