### ISSUE TITLE
Ionide 4 gives less info for this "Note" error

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1129]
**Describe the bug**

Sorry for the name of the issue, I didn't know how to name it 🤷‍♂ 

I am using [Npgsql](http://www.npgsql.org/doc/index.html) in a FAKE script and when trying to get intellisense on the connection I only get `<Note>`.

**To Reproduce**

1. Add `Npgsql` to any FAKE script
2. Add this code:

```fs
open Npgsql

use conn = new NpgsqlConnection("")

conn. // Here request for intellisense
```
3. See the `<Note>` proposition

**Expected behaviour**

When checked if the bug existed in Ionide 3 I discovered that in this version we had more info:

<img width="755" alt="Capture d’écran 2019-06-13 à 09 12 57" src="https://user-images.githubusercontent.com/4760796/59411445-8ddd4480-8dbb-11e9-9328-c227fa10e40e.png">

Can we get the description info back in Ionide 4 too? Because in my case it helped me solve my problem I just added `#r "System.Transactions"` and had intellisense working from here.

**Screenshots**
![2019-06-13 09 04 30](https://user-images.githubusercontent.com/4760796/59411411-7736ed80-8dbb-11e9-9796-278ea0670c87.gif)

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in experimental `0.3.2`

**Comment by MangelMaxime** [comment]
I still have the same result. I see `<Note>` but no description attached to it.

**Comment by inosik** [comment]
FWIW, this happens in VS 2017 as well, and also with other classes that are ADO.NET connections:

![2019-06-18_07-01-37](https://user-images.githubusercontent.com/11393003/59654744-e33c9b80-9197-11e9-80f6-6115dd08aed1.png)

Adding `#r "System.Transactions"` fixes this.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `4.4.x`
