### ISSUE TITLE
FSX files full of errors since 4.1.0

### ISSUE THREAD

**Issue by ronaldschlenker** [ionide/ionide-vscode-fsharp#1220]
Since I updated to 4.1.0, I get a lot of error messages in fsx files.

* It seems that even basic types like string and int cause an error message, as you can see in the attached screenshot.
* When I move back to 4.0.6, it's ok again - no error messages.
* There are a lot more "Code: -32603" error messages in the log (also on the screenshot) - may be related to #1182.

Bug may be related to #1215, but since the described behavior **definitely** came with 4.1.0 (some hours ago), it's propably another issue.

![image](https://user-images.githubusercontent.com/472222/65224941-7ac9c700-dac4-11e9-9c26-50bc6c9d9ebb.png)

**Comment by dlidstrom** [comment]
Yep I am seeing this as well.

**Comment by baronfel** [comment]
Can either of you see if you might be hitting https://github.com/fsharp/FsAutoComplete/issues/457? Essentially I'm wondering if you have mixed file soearator slashes in your project files. If you have the verbose logging on, you can verify this by seeing if the Files property of the 'fsharp/notifyWorkspace' even is an empty array.

**Comment by dlidstrom** [comment]
I have a small project file, just this:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Srtp.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <Import Project="..\fsc.props" />
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>
```

**Comment by MangelMaxime** [comment]
In general, I start my `.fsx` files with:

```fs
#if !FAKE
#r "Facades/netstandard"
#r "netstandard"
```

It required 1-2 years ago. I am not sure if it still the case or no.

**Comment by ollipekka** [comment]
git clean -xdf and good old medicine 'Reload window' sorted this for me which seems strange.

**Comment by isaacabraham** [comment]
I've temporarily fixed this by reverting FSAC to netframework instead of netcore in settings.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `4.2.0`

**Comment by lfr** [comment]
I still have the problem with `4.2.0`, but @isaacabraham's workaround works for me

**Comment by almostSouji** [comment]
I can also still reproduce this with `4.2.0` changing FSAC to `net` does indeed work

**Comment by ValeTheVioletMote** [comment]
Still having this issue in `4.4.2`...

**Comment by davidspiess** [comment]
I still have this problem with `4.9.0`, switched to `net` too.

**Comment by nrolland** [comment]
FWIW I had that pb with some preview versions, uninstalling them with [uninstall tools](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/uninstall-tool?tabs=macos) fixed it
 ```
$ dotnet --info                                                                                
..
Host (useful for support):
  Version: 5.0.0-preview.4.20251.6
  Commit:  47ec733ba7
```

after uninstall

 ```
$ dotnet --info              
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.300/

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6
```

**Comment by ErikSchierboom** [comment]
I'm using the .NET 5 SDK and had the same issue. Reverting back to the .NET backend fixes it.
