### ISSUE TITLE
Rename of function and type does not work

### ISSUE THREAD

**Issue by stoft** [ionide/ionide-vscode-fsharp#1265]
**Describe the bug**
F2/rename of a function name or type name simply does not work. (It does work on function parameters.)

**To Reproduce**
Steps to reproduce the behaviour:
1. `dotnet new console -lang F# -o RenameError`
2. `cd RenameError`
3. `code .`
4. Open `Program.fs``
5. Click on the `main` function
6. Press F2 (rename symbol) and type a different name
7. Press enter

**Expected behaviour**
The function name is renamed to the different name.

**Environment (please complete the following information):**
 - OS: MacOS Catalina 10.15.1
 - Ionide version: 4.3.2
 - VSCode version: 1.40.2
 - dotnet SDK version: 3.1.100
 - mono / .Net Framework version: 6.4.0.198

**Additional context**
With verbose logging set to `true` in settings I get the following in the F# output:

```
[FSharpChecker] Current Queue Length: 0
[Checker] TryGetRecentCheckResultsForFile - /Users/rala/Projects/fsharp/RenameError/Program.fs
[LSP call] TextDocumentRename
[LSP] PositionHandler - Position request: /Users/rala/Projects/fsharp/RenameError/Program.fs at (6,7)
[FSharpChecker] Current Queue Length: 0
[Checker] TryGetRecentCheckResultsForFile - /Users/rala/Projects/fsharp/RenameError/Program.fs
```

Let me know if there are other logging or debugging settings I can tweak.

**Comment by Krzysztof-Cieslak** [comment]
This should be fixed in `4.4.4`

**Comment by stoft** [comment]
Still not fixed unfortunately. Let me know if there's any way I can help debug this.

**Comment by nhirschey** [comment]
I am getting the same issue, rename and show references does not work on .fsx.

Repro:
1. Create new empty folder
```
mkdir test
cd test
```
2. Save file called `test.fsx` with
```fsharp
let x = 4.0

printfn "%A" x
```
3. Try show all references or rename symbol to change `x` into `y`.
<img width="872" alt="Screenshot 2021-02-10 113906" src="https://user-images.githubusercontent.com/5226115/107505487-ab684000-6b94-11eb-985a-a7e7a276409b.png">


System info:
-Version: 1.53.0 (user setup)
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by bytesource** [comment]
I have the same issue. Renaming only works inside a function.

**Comment by bytesource** [comment]
Would it be possible to reopen this issue? 

I tried deleting `symbolCache.db`, but I still cannot rename symbols in a `.fsx` file. Renaming only works for symbols inside a function.

If there's any data I could provide you with, just let me know, and I'll add it here.

**Comment by cartermp** [comment]
I'll re-open this since it is trivially reproducible with @nhirschey's steps with the latest Ionide. Symbol highlighting does work - the edito can pick up that `x` is the same `x` as is defined earlier, and if you shadow it with another `x` it will pick up the shadowed value. I suspect there's a bug in the FSAC version used in the latest Ionide.

**Comment by bytesource** [comment]
After updating to Ionide version 5.5.2 I tried again to rename a function name in a `fsx` file, but it still doesn't work. However, I now receive the following error message when pressing `Enter` after renaming: 

> Cached typecheck results not yet available

Could this be helpful in solving the issue?

Being able to rename function names is such a godsend, and I'd love to have this features available in `fsx` files, too. 

If you need any additional information, just let me know. 

**EDIT**:
After trying again, I received yet another error message:

`Unknown workspace edit change received: { "textDocument": { "uri": "file:///d%3A/Documents/Programming/Fsharp/HSKCloze/Pinyin.fsx" }, "edits": [ { "range": { "start": { "line": 267, "character": 4 }, "end": { "line": 267, "character": 16 } }, "newText": "catSegmenter2" }, { "range": { "start": { "line": 302, "character": 24 }, "end": { "line": 302, "character": 36 } }, "newText": "catSegmenter2" } ] }`

**Comment by nhirschey** [comment]
@bytesource On 5.5.2, stable (not insiders) vscode, I am able to rename and find all references successfully given the repro of the problem in my comment earlier in the thread. I can switch back and forth between renaming the variable x and y.

One time it did not work, but then I saved the file and it started working again.

Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by bytesource** [comment]
@nhirschey, I tried what you did and... now it's working! It's fantastic! 

Has this issue been fixed recently or was it just a glitch (for lack of a better term) with my setup?

**Comment by nhirschey** [comment]
I believe it was fixed in this week’s release by some off by one errors @baronfel fixed in fsautocomplete.

@baronfel I think you can close this issue. Thank you for those fixes!

**Comment by bytesource** [comment]
@nhirschey I see, that's great. @baronfel, thanks a lot for bringing back autocomplete to `fsx` files!

**Comment by baronfel** [comment]
Glad that things are ok for you all :)

**Comment by LiteracyFanatic** [comment]
Rename is still broken for me with Ionide v5.5.5 and fsautocomplete v0.46.0. OS is Arch Linux. More specifically, the issue seems to happen when the type I'm trying to rename is used within an implementation of an interface for a class in a separate file. I've posted the smallest reproduction I've been able to come up with.

RenameTest.fsproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>RenameTest</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Domain.fs" />
    <Compile Include="IFooPrinter.fs" />
    <Compile Include="FooPrinter.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
```

Domain.fs
```fsharp
namespace Domain

type Foo = {
    A: int
    B: string
}
```

IFooPrinter.fs
```fsharp
namespace Services

open Domain

type IFooPrinter =
    abstract PrintFoo: foo: Foo -> unit
```

FooPrinter.fs
```fsharp
namespace Services

open Domain

type FooPrinter() =
    interface IFooPrinter with
        member this.PrintFoo(foo: Foo) =
            printfn $"A = %i{foo.A}, B = %s{foo.B}"
```

Program.fs
```fsharp
open Domain
open Services

[<EntryPoint>]
let main argv =
    let foo = {
        A = 1
        B = "2"
    }
    let fooPrinter = FooPrinter() :> IFooPrinter
    fooPrinter.PrintFoo(foo)
    0
```

Opening `Domain.fs` and trying to rename `Foo` results in the following error message where the line number for the range is off by one.

```json
Unknown workspace edit change received:
{
    "textDocument": {
        "uri": "file:///home/jordan/src/RenameTest/IFooPrinter.fs"
    },
    "edits": [
        {
            "range": {
                "start": {
                    "line": 5,
                    "character": 28
                },
                "end": {
                    "line": 5,
                    "character": 31
                }
            },
            "newText": "Bar"
        }
    ]
}
```

Sometimes after editing and saving `FooPrinter.fs` renaming starts to work, but this doesn't happen reliably.

**Comment by nhirschey** [comment]
@LiteracyFanatic you say
> Sometimes after editing and saving `FooPrinter.fs` renaming starts to work, but this does not happen reliably.

This makes me wonder, when renaming does not work for you, is type checking working? I have found that renaming will not work and I get errors like the one you provide if type checking is broken as described in this issue https://github.com/ionide/ionide-vscode-fsharp/issues/1500 (I give a script issue, but booksbaum gives a project example). However as long as the file is properly getting typechecked then renaming is fine.

Do the workarounds described in that issue to bring back type-checking cause rename to start working again for you? Specifically, closing the files, closing the folder, then reopening?

**Comment by LiteracyFanatic** [comment]
@nhirschey

Good question. While I do run into the issue you linked at times as well, I can reproduce the behavior related to renaming while type checking is working fine for me i.e. line lenses are displayed and I can hover over values to see their type information displayed. It's just the rename command which is failing. Unfortunately, I have yet to find a consistent way to fix it. I've messed around with editing and saving the file, clearing ionide's cache, and opening and closing vs code. Frustratingly, all I can say is that it will sometimes start working and other times will not. It never works when freshly cloning the example I posted though.

**Comment by nhirschey** [comment]
@LiteracyFanatic see this gif. I get line lenses and hover values even though the file is not getting type checked (note the integer in the string list). And rename will also fail. But then if I then do `ctrl-p` to bring up the command window and `>Developer:reload window` it reloads things and type checking + rename works.

![rename-typecheck-issue](https://user-images.githubusercontent.com/5226115/119252607-22a26c80-bba5-11eb-8015-86c16fe106f0.gif)

**Comment by LiteracyFanatic** [comment]
@nhirschey I better understand what you mean now. I tried adding a list similar to yours and it properly typed checked and underlined the integer with red squiggles. Renaming `Foo` still doesn't work though.

I'm fairly certain the issue I'm experiencing is related to interface definitions specifically. I have a medium sized ASP.NET Core project that seemingly randomly refuses to let me rename things. Values inside a function work fine, but types are hit and miss. Even with two records defined in the same file, one will rename fine and the other won't. My attempts to reproduce in a test project kept failing.

Finally I realized that all of the types that wouldn't rename appeared in a class implementing an interface I was injecting into the dependency container. Any types which where only being used in functions or class members that didn't belong to an interface would rename fine. Unfortunately that means 90% of my domain and data model types won't rename.

**Comment by seanamos** [comment]
I still run into this regularly and it's quite easy to reproduce as well.
I don't get it with locally scoped variables, but with high level scopes (Modules/module level functions/types), it's quite often the rename will fail with an error:
```
Unknown workspace edit change received: { "textDocument": { "uri": "file:///xxx.fs" }, "edits": [ { "range": { "start": { "line": 55, "character": 26, "debuggerDisplay": "(55,26)" }, "end": { "line": 55, "character": 37, "debuggerDisplay": "(55,37)" }, "debuggerDisplay": "(55,26)-(55,37)" }, "newText": "MakeContext" } ] }
```

Not sure if it helps at all, but the start/end line characters don't line up with any source code. That is to say, the character runs past the length of the line. The start/end ranges also seem in the nearby vicinity of something that should get renamed (1 line+-) but are off.

**Comment by rosund2** [comment]
I am running into this when working on scripts. Normal fs files works fine. 

![debug1](https://user-images.githubusercontent.com/2396022/148680302-5e0520d0-e534-478a-8ffe-96fc49502973.PNG)

trying to rename logger to asd:

![debug2](https://user-images.githubusercontent.com/2396022/148680339-2f9644f0-3586-4e08-ba0d-d3ca0b8d061e.PNG)

Windows 10, with the latest ionide

![debug3](https://user-images.githubusercontent.com/2396022/148680383-21ab152a-6e0b-4f59-86d8-71e558f505c0.PNG)

**Comment by bytesource** [comment]
Unfortunately, the issue is back for me, too.

**Comment by rosund2** [comment]
Could maybe someone reopen this ?

**Comment by kirse** [comment]
+1 thanks for re-opening this.  Seems to be a recent thing, or maybe it's because my project reached a certain level of complexity to start happening?  Any way to assist with debug?  This also seems to partially bork `Shift+F12` (Find all Refs) and `F12` (Go to Definition) as well which is pretty impactful for dev.  Thanks

Before rename:
![before-rename](https://user-images.githubusercontent.com/3741903/168440688-e0c52468-a84e-4c09-82af-914a1f3f3881.PNG)

After rename (tried to rename `HandleResult` to `HandleResultNEW`:
![after-rename](https://user-images.githubusercontent.com/3741903/168440691-8ecc78ce-c8fd-4c19-94a8-ea27f02b2894.PNG)
!

**Comment by eyassud** [comment]
I am brand new to F# and created a brand new [SAFE ](https://safe-stack.github.io/docs/)application and rename(F2) functionality is not working

**Comment by baronfel** [comment]
sorry about that! we still haven't released the fix in Ionide yet. we're working on it, though!

**Comment by Krzysztof-Cieslak** [comment]
7.0.0 is now released.

**Comment by forki** [comment]
Wohoo!

Krzysztof Cieślak ***@***.***> schrieb am So., 24. Juli 2022,
00:11:
