### ISSUE TITLE
Ionide doesn't find references to almost anything.

### ISSUE THREAD

**Issue by babysnakes** [ionide/ionide-vscode-fsharp#1718]
### Describe the bug
I didn't work on _F#_ project for several months now so I don't know when this happened but when I tried to open an F# project today It didn't find any references to almost all of the symbols I pointed it to. Actually, In my quick tests it only found references to functions within other functions. Anything with larger scope (even within a file) didn't work - It just says `no reference found fot ...`. I couldn't find any related errors in the logs.

### Steps to reproduce
1. Open an _F# project (in my case it was https://github.com/matthewcrews/FSharpPerformance - it contains multiple projects, I opened `TopologicalSort`)
2. Wait for the project to completely load and open a file (In my case `Version1.fs`.
3. Go to a type or function (in my case `sort`).
4. Right click and select _Go To References_ - It should say that no references were found.
5. If you click on a subfunction (e.g. `loop` within `sort`) you'll get the references.

### Link to sample reproduction
I first saw it in the repository linked above but it happened on all F# repositories I have locally on two computers.

### Expected behaviour
Show references.

### Screenshots
![image](https://user-images.githubusercontent.com/31975/171997013-5bf8a6ff-3f8f-430e-bab7-db71e2ea843a.png)

## Machine info
 - OS: Windows (both 10 and 11)
 - .NET SDK version: 6.0.300
 - Ionide version: 6.0.5

### Additional context
 To avoid clashes with other extensions I also tried this on a portable installation without any extensions except _Ionide_ and it was the same behavior.

**Comment by baronfel** [comment]
This should be fixed in the next release we make - references and renames (along with other features that rely on finding symbol uses) had some issues that we've hopefully ironed out.

**Comment by babysnakes** [comment]
This was fast 🙂, 

Thanks

**Comment by babysnakes** [comment]
Hey @baronfel,

I now have version `6.0.6` installed but the problem persists.  Note that going forward (e.g. _go to definition_) does work - also worked in the previous version.

**Comment by baronfel** [comment]
Sorry, I haven't released a version of FSAC with the fix yet - I put out a patch release of Ionide with some other fixes first. I'm doing some perf testing on it before releasing.

**Comment by backerman** [comment]
This bug is fixed in Ionide 7.0.0 with .NET Core 6.0.302 but shows up again in .NET Core 6.0.400-preview.22330.6. (Easy workaround: `local.json` to force the non-preview build).

**Comment by babysnakes** [comment]
@baronfel, It now works again 🙂  (Ionide `7.0.0` with stable .Net 6.0). Should I close this ticket or should I leave it because of what @backerman discovered about preview version?

**Comment by baronfel** [comment]
I made a new issue for the preview problem specifically, so we can close this.
