### ISSUE TITLE
Lint not working

### ISSUE THREAD

**Issue by csmager** [ionide/ionide-vscode-fsharp#220]
This is initially more a question than a bug, as I could well be doing something wrong. I've searched, and I can't find any documentation or explanation as to how this is supposed to work.

The default setting for `FSharp.linter` is `true`, so I'd assume it is enabled.  I'm not seeing any UI that gives me the feedback I see in F# Power Tools in VS 2015. I've added an `Settings.FSharpLint` file in case this was required - again, F# Power Tools in VS 2015 picks this up.

I turned on the debug logging and see entries like this:

>[10:45:46 INFO ] REQ (022) -> {lint}, File = "~\src\abc\def.fs"
[10:45:46 DEBUG] RES (022) <- {lint} in 4 ms: Kind={"error"}
Data="File 'c:\\path\\abc\def.fs' not parsed"

**Comment by Krzysztof-Cieslak** [comment]
Are any other features (autocomplete, error highlighting, tooltips etc) working? 
Can you show full (from start of plugin) log?

**Comment by csmager** [comment]
No issues with anything else - I get auto complete, see CodeLens, the type & docs tool tips, error highlights / tool tips.  I'm using v2.7.1, but this has never worked for me (I've only recently realised it's supposed to be enabled by default).

I created a simple console app, here's the full log from opening folder and clicking `Program.cs`:

>[11:25:24 DEBUG] got FSAC line, is it the started message? true
[11:25:24 DEBUG] FSAC stdout: [I] 2016-10-20T10:25:24.2054001Z: listener started in 17.533 ms with binding 127.0.0.1:8815 [Suave.Tcp.tcpIpServer]
[11:25:24 INFO ] REQ (001) -> {project}, File = "~\IonideTest\IonideTest.fsproj"
[11:25:24 INFO ] REQ (002) -> {lint}, File = "~\IonideTest\Program.fs"
[11:25:24 INFO ] REQ (003) -> {parse}, File = "~\IonideTest\Program.fs"
[11:25:24 DEBUG] RES (002) <- {lint} in 311 ms: Kind={"error"}
Data="File 'c:\\dev\\IonideTest\\IonideTest\\Program.fs' not parsed"
[11:25:24 DEBUG] RES (001) <- {project} in 575 ms: Kind={"project"}
Data={"Project":"c:\\dev\\IonideTest\\IonideTest\\IonideTest.fsproj","Files":["c:\\dev\\IonideTest\\IonideTest\\AssemblyInfo.fs","c:\\dev\\IonideTest\\IonideTest\\Program.fs"],"Output":"c:\\dev\\IonideTest\\IonideTest\\bin\\Debug\\IonideTest.exe","References":["C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\FSharp\\.NETFramework\\v4.0\\4.4.0.0\\FSharp.Core.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Core.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Numerics.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\mscorlib.dll"],"Logs":{"c:\\dev\\IonideTest\\IonideTest\\IonideTest.fsproj":""}}
[11:25:24 INFO ] REQ (004) -> {parse}, File = "~\IonideTest\Program.fs"
[11:25:26 DEBUG] RES (003) <- {parse} in 1886 ms: Kind={"errors"}
Data=[]
[11:25:26 INFO ] REQ (005) -> {declarations}, File = "~\IonideTest\Program.fs"
[11:25:26 DEBUG] RES (004) <- {parse} in 1897 ms: Kind={"errors"}
Data=[]
[11:25:26 INFO ] REQ (006) -> {parseProjects}
[11:25:26 DEBUG] RES (005) <- {declarations} in 339 ms: Kind={"declarations"}
Data=[{"Declaration":{"UniqueName":"Program_1_of_1","Name":"Program","Glyph":"Module","GlyphChar":"N","IsTopLevel":true,"Range":{"StartColumn":1,"StartLine":4,"EndColumn":1,"EndLine":13},"BodyRange":{"StartColumn":1,"StartLine":1,"EndColumn":6,"EndLine":12},"File":"c:\\dev\\IonideTest\\IonideTest\\Program.fs","EnclosingEntity":"M","IsAbstract":false},"Nested":[{"UniqueName":"Program_1_of_1","Name":"main","Glyph":"Function","GlyphChar":"Fc","IsTopLevel":false,"Range":{"StartColumn":5,"StartLine":5,"EndColumn":6,"EndLine":12},"BodyRange":{"StartColumn":5,"StartLine":5,"EndColumn":6,"EndLine":12},"File":"c:\\dev\\IonideTest\\IonideTest\\Program.fs","EnclosingEntity":"M","IsAbstract":false}]}]
[11:25:26 DEBUG] RES (006) <- {parseProjects} in 96 ms: Kind={"errors"}
Data=[]
[11:25:26 INFO ] REQ (007) -> {project}, File = "~\IonideTest\IonideTest.fsproj"
[11:25:26 DEBUG] RES (007) <- {project} in 3 ms: Kind={"project"}
Data={"Project":"c:\\dev\\IonideTest\\IonideTest\\IonideTest.fsproj","Files":["c:\\dev\\IonideTest\\IonideTest\\AssemblyInfo.fs","c:\\dev\\IonideTest\\IonideTest\\Program.fs"],"Output":"c:\\dev\\IonideTest\\IonideTest\\bin\\Debug\\IonideTest.exe","References":["C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\FSharp\\.NETFramework\\v4.0\\4.4.0.0\\FSharp.Core.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Core.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Numerics.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\mscorlib.dll"],"Logs":{"c:\\dev\\IonideTest\\IonideTest\\IonideTest.fsproj":""}}
[11:25:27 INFO ] REQ (008) -> {tooltip}, File = "~\IonideTest\Program.fs"
[11:25:27 DEBUG] RES (008) <- {tooltip} in 150 ms: Kind={"tooltip"}
Data=[[{"Signature":"val main : argv:string [] -> int\n\nFull name: Program.main","Comment":""}]]
[11:25:32 INFO ] REQ (009) -> {project}, File = "~\IonideTest\IonideTest.fsproj"
[11:25:32 INFO ] REQ (010) -> {lint}, File = "~\IonideTest\Program.fs"
[11:25:32 DEBUG] RES (009) <- {project} in 9 ms: Kind={"project"}
Data={"Project":"c:\\dev\\IonideTest\\IonideTest\\IonideTest.fsproj","Files":["c:\\dev\\IonideTest\\IonideTest\\AssemblyInfo.fs","c:\\dev\\IonideTest\\IonideTest\\Program.fs"],"Output":"c:\\dev\\IonideTest\\IonideTest\\bin\\Debug\\IonideTest.exe","References":["C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\FSharp\\.NETFramework\\v4.0\\4.4.0.0\\FSharp.Core.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Core.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Numerics.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\mscorlib.dll"],"Logs":{"c:\\dev\\IonideTest\\IonideTest\\IonideTest.fsproj":""}}
[11:25:32 INFO ] REQ (011) -> {parse}, File = "~\IonideTest\Program.fs"
[11:25:32 DEBUG] RES (011) <- {parse} in 9 ms: Kind={"errors"}
Data=[]
[11:25:32 DEBUG] RES (010) <- {lint} in 219 ms: Kind={"lint"}
Data=[]
[11:25:33 INFO ] REQ (012) -> {project}, File = "~\IonideTest\IonideTest.fsproj"
[11:25:33 INFO ] REQ (013) -> {lint}, File = "~\IonideTest\Program.fs"
[11:25:33 DEBUG] RES (012) <- {project} in 5 ms: Kind={"project"}
Data={"Project":"c:\\dev\\IonideTest\\IonideTest\\IonideTest.fsproj","Files":["c:\\dev\\IonideTest\\IonideTest\\AssemblyInfo.fs","c:\\dev\\IonideTest\\IonideTest\\Program.fs"],"Output":"c:\\dev\\IonideTest\\IonideTest\\bin\\Debug\\IonideTest.exe","References":["C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\FSharp\\.NETFramework\\v4.0\\4.4.0.0\\FSharp.Core.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Core.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Numerics.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\mscorlib.dll"],"Logs":{"c:\\dev\\IonideTest\\IonideTest\\IonideTest.fsproj":""}}
[11:25:33 INFO ] REQ (014) -> {parse}, File = "~\IonideTest\Program.fs"
[11:25:33 DEBUG] RES (013) <- {lint} in 10 ms: Kind={"lint"}
Data=[]
[11:25:33 DEBUG] RES (014) <- {parse} in 18 ms: Kind={"errors"}
Data=[]

**Comment by Krzysztof-Cieslak** [comment]
Looks like at the end it just returns empty array so it suggest that there are no problems in this file?
```
[11:25:33 DEBUG] RES (013) <- {lint} in 10 ms: Kind={"lint"}
Data=[]
```

**Comment by csmager** [comment]
At the moment I have the `Settings.FSharpLint` file [from the `FSharpLint project](https://github.com/fsprojects/FSharpLint/blob/e5b031b98a88720bae3a015823d620435817e77a/Settings.FSharpLint) in the root directory and the code in Program.cs is this:
```fsharp
type blah = 
    { arg : int }

[<EntryPoint>]
let main argv = 

    let a = 1
    let b = 2    
    let c = not (a = b)

    printfn "%A" c
    0 // return an integer exit code
```
VS 2015 with F# Power Tools is showing me that `blah` should be pascal case, `arg` should be pascal case, that it found trailing whitespace after `let b = 2    ` and that `not (a = b)` might be able to be refactored to `a <> b`.

**Comment by Krzysztof-Cieslak** [comment]
CC: @duckmatt

**Comment by duckmatt** [comment]
I seem to be able to repeat, will try to put together a fix

![image](https://cloud.githubusercontent.com/assets/3247369/19622873/9d9ed7d2-98ac-11e6-9527-8d230bc3db35.png)

**Comment by duckmatt** [comment]
Submitted a PR which fixes the error in the screenshot I added

**Comment by csmager** [comment]
Excellent. Many thanks!

**Comment by Krzysztof-Cieslak** [comment]
Fix released in `2.8.3`

**Comment by csmager** [comment]
Sorry to be a buzz-kill, but I just re-ran the same test again and I'm still not getting any lint issues returned, still just an empty array,  I don't see any errors in the Console,

**Comment by vasily-kirichenko** [comment]
@csmager change anything in the file and they will appear.

**Comment by csmager** [comment]
@vasily-kirichenko I did spot your issue shortly afterwards - I tried that, still nothing. I've never seen this work since I started using VS Code on any of three machines. I don't know if it's something related to my setup (I know I had issues early on as I didn't have VS 2013 / MSBuild 12.0 installed) or just bad luck!
