### ISSUE TITLE
Bug in Forge calls on Windows when User has space in username

### ISSUE THREAD

**Issue by robertmaxton42** [ionide/ionide-vscode-fsharp#368]
When generating Forge calls (for example, when calling `F#: Add Reference` or `Remove Reference`), the generated command-line does not properly quote or escape the generated filename. As a result, the command terminates early with an invalid location and generates an error. 

Example:

```
forge add reference -n System.Drawing -p c:\Users\Robert Maxton\Documents\F#\HoughTransform\HoughTransform.fsproj --no-prompt
Unhandled error:
Could not find file 'c:\Users\Robert'.
```

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.23.3`

**Comment by robertmaxton42** [comment]
While the primary issue has indeed been fixed, when adding a custom (i.e. non-Framework) reference with spaces in the path, a similar error persists. 

`forge add reference -n C:\Users\Robert Maxton\Downloads\AForge.NET Framework-2.2.5-(libs only)\Release\AForge.Math.dll -p "c:\Users\Robert Maxton\Documents\F#\HoughTransform\HoughTransform.fsproj" --no-prompt`

Workaround: manually adding quotes around the path also adds them to the command correctly.

**Comment by robertmaxton42** [comment]
A similar error exists with `>F#: Add File to Project` and the corresponding command `forge add file`.
