### ISSUE TITLE
BuildFrameworkTcImports: no resolution of FSharp.Core, Version=4.4.1.0

### ISSUE THREAD

**Issue by kostrse** [ionide/ionide-vscode-fsharp#389]
F# projects with FSharp.Core library 4.4.1.0 do not work in VS Code 1.10.x

Error message:
```
file: 'file:///startup'
severity: 'Error'
message: 'internal error: BuildFrameworkTcImports: no resolution of 'FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a''
at: '1,1'
source: ''
```

Reference in my project file:
```xml
<Reference Include="FSharp.Core">
  <Name>FSharp.Core</Name>
  <AssemblyName>FSharp.Core.dll</AssemblyName>
  <HintPath>$(MSBuildProgramFiles32)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\$(TargetFSharpCoreVersion)\FSharp.Core.dll</HintPath>
</Reference>
```

The library itself exist, and the project works well in Visual Studio 2017.

[A related link to StackOverflow](http://stackoverflow.com/questions/42578595/getting-internal-error-buildframeworktcimports-no-resolution-of-fsharp-core)

**Comment by YoLieR** [comment]
same problem here.

**Comment by abhiranjankumar00** [comment]
+1

**Comment by drewcarver** [comment]
Also experiencing the same issue.

**Comment by lilred** [comment]
I have a student here with this issue. Windows 10, Ionide 2.24.1. Working on a single file, no project file.

Any work-arounds?

**Comment by Krzysztof-Cieslak** [comment]
I think that adding project file and setting FSharp.Core version to `4.4.0.0` or using FSharp.Core from NuGet should fix issue

**Comment by vrnithinkumar** [comment]
After adding the project file the error is not coming.

**Comment by bytos** [comment]
Having the same issue.

**Comment by efvincent** [comment]
Also having the same problem. Does this mean that ionide is not working for anyone right now?

**Comment by Kurren123** [comment]
Having the same problem on ionide. I created a new project using the dotnet CLI tools described in [this tutorial](https://docs.microsoft.com/en-us/dotnet/articles/fsharp/tutorials/getting-started/getting-started-command-line).

**Comment by Kurren123** [comment]
@efvincent Yes this looks like a bug that's stopping ionide from functioning right now

**Comment by Kurren123** [comment]
@Krzysztof-Cieslak I'd like to add that I get this error even when setting `<TargetFSharpCoreVersion>4.4.0.0</TargetFSharpCoreVersion>` in the project file and also using FsharpCore from nuget.

**Comment by ntwilson** [comment]
@Krzysztof-Cieslak I'd like to further add I have a multi-project solution (net45).  When I switch to `<TargetFSharpCoreVersion>4.4.0.0</TargetFSharpCoreVersion>` the project furthest up the dependency chain (doesn't depend on any other projects) works fine with ionide, but projects that depend on it exhibit the error.  (The solution is a mix of F# and C# projects)

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `2.25.4`

**Comment by smotti** [comment]
Still encounter that issue.
After creating a new project everything works but suddenly after a few minutes (maybe after the first build) it throws that error. Which also results in 'not parsed' errors for the source files, thus no linting, type hinting, etc works.

**Comment by darky** [comment]
`3.10.1` also affected
