### ISSUE TITLE
VSCode cannot find System.Net

### ISSUE THREAD

**Issue by badgh** [ionide/ionide-vscode-fsharp#51]
Anybody had this issue? How to fix it? VSCode cannot find namespace System.Net:
![systemnetissue](https://cloud.githubusercontent.com/assets/10549729/14139545/6a893ffe-f67c-11e5-8e07-2320268266a5.png)

**Comment by Krzysztof-Cieslak** [comment]
Can you try running Project Cracker on your `fsproj` file? `FSharp.Compiler.Service.ProjectCrackerTool.exe --text <path to>/console.fsproj true`. `FSharp.Compiler.Service.ProjectCrackerTool.exe` is present in extension installation folder in `bin` directory.

**Comment by bdpy** [comment]
`fsproj ` file is related to Visual Studio 2015? But this is just a Visual Studio Code folder opened (no `fsproj` for VSCode). I have a folder opened in VSCode which has one file `Program.fs` to play with.

**Comment by bdpy** [comment]
Is there a way for `ionide-vscode-fsharp` to reference F# 4.0 assemblies, rather than F# 3.1.2?

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in latest release.

**Comment by rahulpnath** [comment]
@Krzysztof-Cieslak I still see this error. I am running 2.9.1 ionide-fsharp. Anything that I am missing?
