### ISSUE TITLE
VSCode not compiling my code/broken

### ISSUE THREAD

**Issue by haf** [ionide/ionide-vscode-fsharp#524]
<img width="400" alt="screen shot 2017-09-04 at 15 48 23" src="https://user-images.githubusercontent.com/193115/30029185-82a9d780-9188-11e7-8647-52b1f63b8e16.png">

 - Mono 5.2.0.x
 - MacOS
 - .Net Core 2.0
 - Latest Ionide/VSCode
 - No mono through homebrew installed
 - No output in the VSCode F# language server
 - Lots of output corresponding to the errors shown in the screenshot in the debug console, but also these:

```
...
[15:46:01 ERROR] Cannot execute signatureData, Position is out of range 
...
[15:46:02 ERROR] Cannot execute finddeclaration, Could not find declaration 
...
[15:46:21 ERROR] Cannot execute signatureData, File '/Users/h/dev/Api/extension-output-#4.fsx' not parsed 
...
```

I have a hunch this due to changes in how paket installed nugets for unrelated platforms:

<img width="566" alt="screen shot 2017-09-04 at 15 50 55" src="https://user-images.githubusercontent.com/193115/30029304-08676374-9189-11e7-955e-8605a55549c6.png">

But the platform I target is this:

```xml
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{55CD61E6-50FC-4288-A09B-BB47A374EFB4}</ProjectGuid>
    <OutputType>Exe</OutputType>
    <RootNamespace>Api</RootNamespace>
    <AssemblyName>Api</AssemblyName>
    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
```

**Comment by enricosada** [comment]
@haf the open error is because the project wasnt parsed correctly.

Reading https://github.com/fsprojects/Paket/issues/2718 discussion seems fixed now right?

**Comment by haf** [comment]
No, that's a separate discussion. This project is still broken when multi-targeting.

**Comment by enricosada** [comment]
`F# Language Service` output? please enable the log https://github.com/ionide/ionide-vscode-fsharp#how-to-get-logs-for-debugging--issue-reporting

The error should be the response (`RES`) of the first `project` request

**Comment by enricosada** [comment]
@haf can you also add the fsproj? 
i dont need the source files. just the fsproj/paket.lock/paket.deps

**Comment by Krzysztof-Cieslak** [comment]
No reproduction, please reopen if you can provide simple way to reproduce
