### ISSUE TITLE
file not found if "fsacRuntime"="netcore"

### ISSUE THREAD

**Issue by vilinski** [ionide/ionide-vscode-fsharp#656]
File not found error if subject option is `netcore` in new ionide, `net` works as always before.

```
[17:49:15 DEBUG] RES (1314) <- {parse} in 43 ms: Kind={"info"}
Data="Request cancelled (exn was System.ComponentModel.Win32Exception (0x80004005): Das System kann die angegebene Datei nicht finden
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at FsAutoComplete.Utils.runProcess(FSharpFunc`2 log, String workingDir, String exePath, String args)
at Dotnet.ProjInfo.Inspect.msbuild[a](MSBuildExePath msbuildExe, FSharpFunc`2 run, String project, FSharpList`1 args)
at Dotnet.ProjInfo.Inspect.getProjectInfoOldSdk[a,b,c,d](FSharpFunc`2 log, FSharpFunc`2 msbuildExec, FSharpFunc`2 getArgs, FSharpList`1 additionalArgs, a projPath)
at FsAutoComplete.NETFrameworkInfoProvider.getInfoFromMsbuild[a](FSharpFunc`2 getArgs, FSharpList`1 additionalProps)
at FsAutoComplete.NETFrameworkInfoProvider.getInstalledNETVersions() in D:\\Programowanie\\ionide\\paket-files\\github.com\\fsharp\\FsAutoComplete\\src\\FsAutoComplete.Core\\NETFrameworkInfoProvider.fs:line 99
at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Lazy`1.CreateValue()
at FsAutoComplete.Environment.netReferecesAssembliesTFMLatest() in D:\\Programowanie\\ionide\\paket-files\\github.com\\fsharp\\FsAutoComplete\\src\\FsAutoComplete.Core\\Environment.fs:line 42
at <StartupCode$FsAutoComplete-Core>.$CompilerServiceInterface.GetProjectOptionsFromScript@328.Invoke(Unit unitVar) in D:\\Programowanie\\ionide\\paket-files\\github.com\\fsharp\\FsAutoComplete\\src\\FsAutoComplete.Core\\CompilerServiceInterface.fs:line 328
at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args))"
```

windows 10
VSCode: 1.18.1
Ionide: 3.13.0
dotnet --version: 2.0.2

**Comment by enricosada** [comment]
thx for bugreport @vilinski

**Comment by enricosada** [comment]
as a note @vilinski that's because you opened an fsx script  (or is somehow parsed) and you didnt have `msbuild` in PATH (is not yet configurable/autodiscovered).

- on Windows usually mean open VSCode from Developer Command Prompt for VS
- or mac/linux mean having mono >= 5.2 installed

meanwhile i'll fix the error

**Comment by vilinski** [comment]
Thanks for clearance. Don't know why msbuild is missing here. I never use command prompt of @drunkvs, but often start "code" from git bash. Error comes for me only on windows and only with `netcore` option.

It was a folder with *.fsx files without any *.sln or *.fsproj files.

No errors on mac however:
```
$ mono --version
Mono JIT compiler version 5.2.0.215 ...
$ dotnet --version
2.0.3
```

**Comment by enricosada** [comment]
Ah nice, thx for additional info. i'll try in git bash too.
i dont use vs prompt, but i have msbuild in PATH, that's why i didnt see that error in testing.

the `.fsx` parsing with `net` option, there was no need for `msbuild` in PATH (msbuild was bundled as library).

the `.fsx` parsing with `netcore` option, doesnt bundle msbuild, instead call `msbuild` 
 executable (it's used to find the `System` assemblies).
But is a temporary requirement, need just better defaults to find the installed location, so will find that anyway, also if not already in PATH

ref https://github.com/fsharp/FsAutoComplete/issues/213

**Comment by inosik** [comment]
I created a shim on my `PATH` which aliases `dotnet msbuild` as `msbuild` and now `.fsx` files work fine with `fsacRuntime: netcore`.

**Comment by TheAngryByrd** [comment]
I have a similar issue with `netcore` and `.fsx` files

```
19:54:24 DEBUG] WebSocket message: '{"Kind":"errors","Data":{"File":"somerepo/build.fsx","Errors":[{"FileName":"commandLineArgs","StartLine":0,"EndLine":0,"StartColumn":1,"EndColumn":1,"Severity":"Error","Message":"Multiple references to 'mscorlib.dll' are not permitted","Subcategory":"parameter"},{"FileName":"commandLineArgs","StartLine":0,"EndLine":0,"StartColumn":1,"EndColumn":1,"Severity":"Error","Message":"Multiple references to 'mscorlib.dll' are not permitted","Subcategory":"parameter"},{"FileName":"commandLineArgs","StartLine":0,"EndLine":0,"StartColumn":1,"EndColumn":1,"Severity":"Error","Message":"Multiple references to 'mscorlib.dll' are not permitted","Subcategory":"parameter"},{"FileName":"somerepo/build.fsx","StartLine":9,"EndLine":9,"StartColumn":15,"EndColumn":50,"Severity":"Error","Message":"The type referenced through 'System.String' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime'.","Subcategory":"typecheck"},{"FileName":"somerepo/build.fsx","StartLine":14,"EndLine":17,"StartColumn":1,"EndColumn":6,"Severity":"Error","Message":"The type referenced through 'System.String' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime'.","Subcategory":"typecheck"},{"FileName":"somerepo/build.fsx","StartLine":19,"EndLine":28,"StartColumn":1,"EndColumn":3,"Severity":"Error","Message":"The type referenced through 'System.String' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime'.","Subcategory":"typecheck"},{"FileName":"somerepo/build.fsx","StartLine":32,"EndLine":47,"StartColumn":1,"EndColumn":2,"Severity":"Error","Message":"The type referenced through 'System.String' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime'.","Subcategory":"typecheck"},{"FileName":"somerepo/build.fsx","StartLine":49,"EndLine":56,"StartColumn":1,"EndColumn":2,"Severity":"Error","Message":"The type referenced through 'System.String' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime'.","Subcategory":"typecheck"},{"FileName":"somerepo/build.fsx","StartLine":58,"EndLine":70,"StartColumn":1,"EndColumn":2,"Severity":"Error","Message":"The type referenced through 'System.String' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime'.","Subcategory":"typecheck"},{"FileName":"somerepo/build.fsx","StartLine":72,"EndLine":76,"StartColumn":1,"EndColumn":16,"Severity":"Error","Message":"The type referenced through 'System.String' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime'.","Subcategory":"typecheck"},{"FileName":"somerepo/build.fsx","StartLine":78,"EndLine":78,"StartColumn":1,"EndColumn":32,"Severity":"Error","Message":"The type referenced through 'System.String' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime'.","Subcategory":"typecheck"},{"FileName":"somerepo/build.fsx","StartLine":1,"EndLine":1,"StartColumn":1,"EndColumn":1,"Severity":"Error","Message":"The type referenced through 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime'.","Subcategory":"typecheck"},{"FileName":"commandLineArgs","StartLine":0,"EndLine":0,"StartColumn":1,"EndColumn":1,"Severity":"Error","Message":"Multiple references to 'mscorlib.dll' are not permitted","Subcategory":"parameter"}]}}'

```

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `3.31.0`

**Comment by 0xaryan** [comment]
I have Ionide `v3.34.0` installed and I still have this issue when `FSharp.fsacRuntime = 'netcore'`. It works well when `FSharp.fsacRuntime = 'net'`.

```
[18:34:27 DEBUG] REQ (025) -> {parse}, File = "~\aryan.fsx"
Data={"FileName":"e:\\Projects\\FSharp\\FAKE\\aryan.fsx","IsAsync":true,"Lines":["open S"],"Version":7}
[18:34:27 DEBUG] RES (025) <- {parse} in 7 ms: Kind={"info"}
Data="Request cancelled (exn was System.ComponentModel.Win32Exception (5): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at FsAutoComplete.Utils.runProcess(FSharpFunc`2 log, String workingDir, String exePath, String args) in D:\\Programowanie\\ionide\\paket-files\\github.com\\fsharp\\FsAutoComplete\\src\\FsAutoComplete.Core\\Utils.fs:line 547
   at Dotnet.ProjInfo.Inspect.msbuild[a](MSBuildExePath msbuildExe, FSharpFunc`2 run, String project, FSharpList`1 args)
   at Dotnet.ProjInfo.Inspect.getProjectInfo[a,b,c](FSharpFunc`2 log, FSharpFunc`2 msbuildExec, FSharpFunc`2 getArgs, FSharpList`1 additionalArgs, String projPath)
   at FsAutoComplete.NETFrameworkInfoProvider.getInfoFromMsbuild[a](FSharpFunc`2 getArgs, FSharpList`1 additionalProps) in D:\\Programowanie\\ionide\\paket-files\\github.com\\fsharp\\FsAutoComplete\\src\\FsAutoComplete.Core\\NETFrameworkInfoProvider.fs:line 26
   at FsAutoComplete.NETFrameworkInfoProvider.getInstalledNETVersions() in D:\\Programowanie\\ionide\\paket-files\\github.com\\fsharp\\FsAutoComplete\\src\\FsAutoComplete.Core\\NETFrameworkInfoProvider.fs:line 72
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at FsAutoComplete.NETFrameworkInfoProvider.netReferecesAssembliesTFMLatest() in D:\\Programowanie\\ionide\\paket-files\\github.com\\fsharp\\FsAutoComplete\\src\\FsAutoComplete.Core\\NETFrameworkInfoProvider.fs:line 159
   at <StartupCode$FsAutoComplete-Core>.$CompilerServiceInterface.GetProjectOptionsFromScript@511.Invoke(Unit unitVar) in D:\\Programowanie\\ionide\\paket-files\\github.com\\fsharp\\FsAutoComplete\\src\\FsAutoComplete.Core\\CompilerServiceInterface.fs:line 511
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction))"
```
