### ISSUE TITLE
Unable to access method quick info as shown in docs

### ISSUE THREAD

**Issue by cpbotha** [ionide/ionide-vscode-fsharp#872]
The documentation at http://ionide.io/docs/editing/ states that I can access method quick info during completion by either clicking on the info icon, or pressing control space.

However, with ionide 3.25.0, vs.code 1.25.1 on macOS 10.13.6, even when I use exactly the same invocation as shown in the documentation, there is no info icon (see my screenshot) and pressing ctrl-space has no additional effect:

![image](https://user-images.githubusercontent.com/937871/43389880-1954ed34-93ed-11e8-827b-b97f8d390785.png)

For comparison, here is the gif from the docs: http://ionide.io/docs/images/autocomplete.gif

Could this be related to issue #871 ?

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `3.25.1`. The problem was related to invalid XML docs in `netstandard.xml` file (Thanks MSFT!)

**Comment by cpbotha** [comment]
I just tried this again with the updated `3.25.1`, but I still can't get the quick info to appear. Icon is not present, Ctrl-Space also does not work. See the screenshot below:

![image](https://user-images.githubusercontent.com/937871/43548420-24bad47a-95de-11e8-8f31-32e104c8e380.png)

(After upgrading the plugin, I also tried restarting vs.code. Is there anything else I could try?)

**Comment by Krzysztof-Cieslak** [comment]
I can't reproduce an issue any more so, it's bit hard for me to fix it.

**Comment by ikzk** [comment]
Same here
<img width="725" alt="2018-09-21_03-03" src="https://user-images.githubusercontent.com/18649508/45865260-e9a60000-bd4a-11e8-8ca4-5812eabead6f.png">

**Comment by Krzysztof-Cieslak** [comment]
Can't reproduce on `4.4.5`

![image](https://user-images.githubusercontent.com/5427083/72651571-ff99f400-3983-11ea-856d-d8d0ab95c7b6.png)
